FROM node:22-slim AS builder
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build


FROM node:22-alpine AS runner 
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder --chown=node:node /app/build build/
COPY --from=builder --chown=node:node /app/node_modules node_modules/
COPY package.json /.
USER node
EXPOSE 3000
CMD [ "node", "build" ]
